[package]
name = "huffman_rs"
version = "0.1.0"
authors = ["wordGiver <wtfbsl0602@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
anyhow = "1.0.34"